// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_hash, label, is_admin, rate_limit_per_minute, tenant_id, created_at, revoked_at, user_id FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Label,
		&i.IsAdmin,
		&i.RateLimitPerMinute,
		&i.TenantID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (id, key_hash, label, is_admin, rate_limit_per_minute, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key_hash, label, is_admin, rate_limit_per_minute, tenant_id, created_at, revoked_at, user_id
`

type InsertAPIKeyParams struct {
	ID                 uuid.UUID
	KeyHash            string
	Label              string
	IsAdmin            bool
	RateLimitPerMinute sql.NullInt32
	TenantID           sql.NullString
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, insertAPIKey,
		arg.ID,
		arg.KeyHash,
		arg.Label,
		arg.IsAdmin,
		arg.RateLimitPerMinute,
		arg.TenantID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Label,
		&i.IsAdmin,
		&i.RateLimitPerMinute,
		&i.TenantID,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, key_hash, label, is_admin, rate_limit_per_minute, tenant_id, created_at, revoked_at, user_id FROM api_keys
WHERE tenant_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID sql.NullString) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.Label,
			&i.IsAdmin,
			&i.RateLimitPerMinute,
			&i.TenantID,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, id)
	return err
}
