// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const getDocumentsByJobID = `-- name: GetDocumentsByJobID :many
SELECT id, job_id, url, markdown, html, raw_html, metadata, status_code, created_at FROM documents
WHERE job_id = $1
ORDER BY id ASC
`

func (q *Queries) GetDocumentsByJobID(ctx context.Context, jobID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Url,
			&i.Markdown,
			&i.Html,
			&i.RawHtml,
			&i.Metadata,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO documents (job_id, url, markdown, html, raw_html, metadata, status_code)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDocumentParams struct {
	JobID      uuid.UUID
	Url        string
	Markdown   sql.NullString
	Html       sql.NullString
	RawHtml    sql.NullString
	Metadata   json.RawMessage
	StatusCode sql.NullInt32
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, insertDocument,
		arg.JobID,
		arg.Url,
		arg.Markdown,
		arg.Html,
		arg.RawHtml,
		arg.Metadata,
		arg.StatusCode,
	)
	return err
}
