// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const getJobByID = `-- name: GetJobByID :one
SELECT id, type, status, url, input, error, created_at, updated_at, completed_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Url,
		&i.Input,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (id, type, status, url, input)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, status, url, input, error, created_at, updated_at, completed_at
`

type InsertJobParams struct {
	ID     uuid.UUID
	Type   string
	Status string
	Url    string
	Input  json.RawMessage
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Url,
		arg.Input,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Url,
		&i.Input,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listPendingCrawlJobs = `-- name: ListPendingCrawlJobs :many
SELECT id, type, status, url, input, error, created_at, updated_at, completed_at FROM jobs
WHERE type = 'crawl' AND status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingCrawlJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCrawlJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Url,
			&i.Input,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2,
    error = $3,
    updated_at = NOW(),
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID
	Status string
	Error  sql.NullString
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.ID, arg.Status, arg.Error)
	return err
}
