// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getJobByID = `-- name: GetJobByID :one
SELECT id, type, status, url, input, error, created_at, updated_at, completed_at, sync, priority, output, tenant_id
FROM jobs
WHERE id = $1
`

type GetJobByIDRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Url         string
	Input       json.RawMessage
	Error       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
	Sync        bool
	Priority    int32
	Output      pqtype.NullRawMessage
	TenantID    uuid.NullUUID
}

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (GetJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Url,
		&i.Input,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Sync,
		&i.Priority,
		&i.Output,
		&i.TenantID,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (id, type, status, url, input, sync, priority, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, type, status, url, input, error, created_at, updated_at, completed_at, sync, priority, output, tenant_id
`

type InsertJobParams struct {
	ID       uuid.UUID
	Type     string
	Status   string
	Url      string
	Input    json.RawMessage
	Sync     bool
	Priority int32
	TenantID uuid.NullUUID
}

type InsertJobRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Url         string
	Input       json.RawMessage
	Error       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
	Sync        bool
	Priority    int32
	Output      pqtype.NullRawMessage
	TenantID    uuid.NullUUID
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (InsertJobRow, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Type,
		arg.Status,
		arg.Url,
		arg.Input,
		arg.Sync,
		arg.Priority,
		arg.TenantID,
	)
	var i InsertJobRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Url,
		&i.Input,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Sync,
		&i.Priority,
		&i.Output,
		&i.TenantID,
	)
	return i, err
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT id, type, status, url, input, error, created_at, updated_at, completed_at, sync, priority, output, tenant_id
FROM jobs
WHERE status = 'pending'
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

type ListPendingJobsRow struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Url         string
	Input       json.RawMessage
	Error       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
	Sync        bool
	Priority    int32
	Output      pqtype.NullRawMessage
	TenantID    uuid.NullUUID
}

func (q *Queries) ListPendingJobs(ctx context.Context, limit int32) ([]ListPendingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingJobsRow
	for rows.Next() {
		var i ListPendingJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Url,
			&i.Input,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Sync,
			&i.Priority,
			&i.Output,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobOutput = `-- name: UpdateJobOutput :exec
UPDATE jobs
SET output = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateJobOutputParams struct {
	ID     uuid.UUID
	Output pqtype.NullRawMessage
}

func (q *Queries) UpdateJobOutput(ctx context.Context, arg UpdateJobOutputParams) error {
	_, err := q.db.ExecContext(ctx, updateJobOutput, arg.ID, arg.Output)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2,
    error = $3,
    updated_at = NOW(),
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID     uuid.UUID
	Status string
	Error  sql.NullString
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.ID, arg.Status, arg.Error)
	return err
}
