// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID                 uuid.UUID
	KeyHash            string
	Label              string
	IsAdmin            bool
	RateLimitPerMinute sql.NullInt32
	TenantID           sql.NullString
	CreatedAt          time.Time
	RevokedAt          sql.NullTime
}

type Document struct {
	ID         int64
	JobID      uuid.UUID
	Url        string
	Markdown   sql.NullString
	Html       sql.NullString
	RawHtml    sql.NullString
	Metadata   json.RawMessage
	StatusCode sql.NullInt32
	CreatedAt  time.Time
	Engine     sql.NullString
}

type Job struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Url         string
	Input       json.RawMessage
	Error       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
	Priority    int32
	Sync        bool
	Output      pqtype.NullRawMessage
}
