// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID                 uuid.UUID
	KeyHash            string
	Label              string
	IsAdmin            bool
	RateLimitPerMinute sql.NullInt32
	TenantID           sql.NullString
	CreatedAt          time.Time
	RevokedAt          sql.NullTime
	UserID             uuid.NullUUID
}

type Document struct {
	ID         int64
	JobID      uuid.UUID
	Url        string
	Markdown   sql.NullString
	Html       sql.NullString
	RawHtml    sql.NullString
	Metadata   json.RawMessage
	StatusCode sql.NullInt32
	CreatedAt  time.Time
	Engine     sql.NullString
}

type Job struct {
	ID          uuid.UUID
	Type        string
	Status      string
	Url         string
	Input       json.RawMessage
	Error       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CompletedAt sql.NullTime
	Priority    int32
	Sync        bool
	Output      pqtype.NullRawMessage
	TenantID    uuid.NullUUID
}

type Tenant struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Type        string
	OwnerUserID uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TenantMember struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	Name            sql.NullString
	AuthProvider    string
	AuthSubject     sql.NullString
	IsSystemAdmin   bool
	PasswordHash    sql.NullString
	PasswordVersion sql.NullInt32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
