// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTenantMember = `-- name: AddTenantMember :one
INSERT INTO tenant_members (tenant_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, user_id) DO UPDATE
SET role = tenant_members.role, updated_at = NOW()
RETURNING tenant_id, user_id, role, created_at, updated_at
`

type AddTenantMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRowContext(ctx, addTenantMember, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantMember = `-- name: GetTenantMember :one
SELECT tenant_id, user_id, role, created_at, updated_at FROM tenant_members
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetTenantMember(ctx context.Context, arg GetTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRowContext(ctx, getTenantMember, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT tenant_id, user_id, role, created_at, updated_at FROM tenant_members
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantMembersParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListTenantMembers(ctx context.Context, arg ListTenantMembersParams) ([]TenantMember, error) {
	rows, err := q.db.QueryContext(ctx, listTenantMembers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantMember
	for rows.Next() {
		var i TenantMember
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantMember = `-- name: RemoveTenantMember :exec
DELETE FROM tenant_members
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantMemberParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RemoveTenantMember(ctx context.Context, arg RemoveTenantMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTenantMember, arg.TenantID, arg.UserID)
	return err
}

const updateTenantMemberRole = `-- name: UpdateTenantMemberRole :one
UPDATE tenant_members
SET role = $3, updated_at = NOW()
WHERE tenant_id = $1 AND user_id = $2
RETURNING tenant_id, user_id, role, created_at, updated_at
`

type UpdateTenantMemberRoleParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

func (q *Queries) UpdateTenantMemberRole(ctx context.Context, arg UpdateTenantMemberRoleParams) (TenantMember, error) {
	row := q.db.QueryRowContext(ctx, updateTenantMemberRole, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
