// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, slug, name, type, owner_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, type, owner_user_id, created_at, updated_at
`

type CreateTenantParams struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Type        string
	OwnerUserID uuid.NullUUID
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Type,
		arg.OwnerUserID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, name, type, owner_user_id, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, type, owner_user_id, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPersonalTenantsForUser = `-- name: ListPersonalTenantsForUser :many
SELECT id, slug, name, type, owner_user_id, created_at, updated_at FROM tenants
WHERE owner_user_id = $1 AND type = 'personal'
ORDER BY created_at ASC
`

func (q *Queries) ListPersonalTenantsForUser(ctx context.Context, ownerUserID uuid.NullUUID) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalTenantsForUser, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, type, owner_user_id, created_at, updated_at FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForUser = `-- name: ListTenantsForUser :many
SELECT tenants.id, tenants.slug, tenants.name, tenants.type, tenants.owner_user_id, tenants.created_at, tenants.updated_at FROM tenants
JOIN tenant_members ON tenant_members.tenant_id = tenants.id
WHERE tenant_members.user_id = $1
ORDER BY tenants.created_at DESC
`

func (q *Queries) ListTenantsForUser(ctx context.Context, userID uuid.UUID) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
