// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1 = '' OR email ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) AdminCountUsers(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminCountUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at FROM users
WHERE ($1 = '' OR email ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type AdminListUsersParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, adminListUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AuthProvider,
			&i.AuthSubject,
			&i.IsSystemAdmin,
			&i.PasswordHash,
			&i.PasswordVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultTenantID,
			&i.ThemePreference,
			&i.IsDisabled,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserPassword = `-- name: AdminSetUserPassword :one
UPDATE users
SET
    password_hash = $2,
    password_version = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at
`

type AdminSetUserPasswordParams struct {
	ID              uuid.UUID
	PasswordHash    sql.NullString
	PasswordVersion sql.NullInt32
}

func (q *Queries) AdminSetUserPassword(ctx context.Context, arg AdminSetUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminSetUserPassword, arg.ID, arg.PasswordHash, arg.PasswordVersion)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET
    name = $2,
    is_system_admin = $3,
    is_disabled = $4,
    disabled_at = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at
`

type AdminUpdateUserParams struct {
	ID            uuid.UUID
	Name          sql.NullString
	IsSystemAdmin bool
	IsDisabled    bool
	DisabledAt    sql.NullTime
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateUser,
		arg.ID,
		arg.Name,
		arg.IsSystemAdmin,
		arg.IsDisabled,
		arg.DisabledAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	Name            sql.NullString
	AuthProvider    string
	AuthSubject     sql.NullString
	IsSystemAdmin   bool
	PasswordHash    sql.NullString
	PasswordVersion sql.NullInt32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AuthProvider,
		arg.AuthSubject,
		arg.IsSystemAdmin,
		arg.PasswordHash,
		arg.PasswordVersion,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByProviderSubject = `-- name: GetUserByProviderSubject :one
SELECT id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at FROM users WHERE auth_provider = $1 AND auth_subject = $2
`

type GetUserByProviderSubjectParams struct {
	AuthProvider string
	AuthSubject  sql.NullString
}

func (q *Queries) GetUserByProviderSubject(ctx context.Context, arg GetUserByProviderSubjectParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderSubject, arg.AuthProvider, arg.AuthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = $2,
    theme_preference = $3,
    default_tenant_id = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, auth_provider, auth_subject, is_system_admin, password_hash, password_version, created_at, updated_at, default_tenant_id, theme_preference, is_disabled, disabled_at
`

type UpdateUserProfileParams struct {
	ID              uuid.UUID
	Name            sql.NullString
	ThemePreference string
	DefaultTenantID uuid.NullUUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.ThemePreference,
		arg.DefaultTenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.IsSystemAdmin,
		&i.PasswordHash,
		&i.PasswordVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultTenantID,
		&i.ThemePreference,
		&i.IsDisabled,
		&i.DisabledAt,
	)
	return i, err
}
